[package]
name = "ramsey"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "6f870fad180eb0f5d8f1e4f385216c25513cb2f8"}
